export const projects = [
  {
    id: 'tech-hub-workspace',
    name: 'TECH HUB WORKSPACE',
    category: 'Office Interior',
    year: '2024',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://images.unsplash.com/photo-1541888946425-d81bb19480c5?auto=format&fit=crop&q=80&w=1400',
    description: 'We transformed an underutilized warehouse into a vibrant, multi-functional tech hub that brings interactive collaboration and modern aesthetics to the forefront. Perfect for agile teams and dynamic workflows.',
    areaSize: '4,500 sq ft',
    completionTime: '8 Weeks',
    scopeOfWork: 'Complete Design & Build, MEP Installation, Acoustic Paneling',
  },
  {
    id: 'executive-boardroom',
    name: 'EXECUTIVE BOARDROOM',
    category: 'Corporate Design',
    year: '2024',
    image: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://plus.unsplash.com/premium_photo-1661877303180-19a028c21048?auto=format&fit=crop&q=80&w=1400',
    description: 'A dedicated executive meeting environment designed for maximum focus, privacy, and architectural elegance. The project involved custom woodwork and precision AV systems.',
    areaSize: '1,200 sq ft',
    completionTime: '12 Weeks',
    scopeOfWork: 'AV Integration, Custom Millwork, Ergonomic Seating',
  },
  {
    id: 'creative-studio',
    name: 'CREATIVE STUDIO',
    category: 'Workspace',
    year: '2023',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&q=80&w=1400',
    description: 'Designed as a creative sanctuary, this studio features modular furniture encased in a sleek, minimalist aesthetic. The perfect environment for brainstorming and innovation.',
    areaSize: '800 sq ft',
    completionTime: '6 Weeks',
    scopeOfWork: 'Lighting Design, Modular Zones, Floor Resurfacing',
  },
  {
    id: 'modern-law-firm',
    name: 'MODERN LAW FIRM',
    category: 'Professional Interior',
    year: '2023',
    image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=1400',
    description: 'A sophisticated law firm interior blending seamlessly into the surrounding corporate architecture. Features glass partition edges and advanced soundproofing to maintain confidentiality.',
    areaSize: '1,500 sq ft',
    completionTime: '14 Weeks',
    scopeOfWork: 'Glass Partitions, Soundproofing, Premium Finishes',
  },
  {
    id: 'open-plan-office',
    name: 'OPEN PLAN OFFICE',
    category: 'Commercial Space',
    year: '2022',
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://images.unsplash.com/photo-1504307651254-35680f33650c?auto=format&fit=crop&q=80&w=1400',
    description: 'A sweeping open plan office installation offering a seamless transition between work zones. Designed with ultimate flexibility and team unity in mind.',
    areaSize: '6,000 sq ft',
    completionTime: '20 Weeks',
    scopeOfWork: 'Zonal Strategy, Biophilic Design, Workstation Layout',
  },
  {
    id: 'boutique-clinic',
    name: 'BOUTIQUE CLINIC',
    category: 'Healthcare Design',
    year: '2022',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://images.unsplash.com/photo-1536154800961-9920ffae73e3?auto=format&fit=crop&q=80&w=1400',
    description: 'A fully soothing boutique clinic utilizing natural light and warm materials rather than harsh sterile palettes. Blends beautifully with organic waiting lounges.',
    areaSize: '3,200 sq ft',
    completionTime: '16 Weeks',
    scopeOfWork: 'Clinical Zoning, Ambient Lighting, Patient Flow Strategy',
  },
  {
    id: 'luxury-retail',
    name: 'LUXURY RETAIL',
    category: 'Retail Interior',
    year: '2021',
    image: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://images.unsplash.com/photo-1534237710431-e2fc698436d0?auto=format&fit=crop&q=80&w=1400',
    description: 'A high-end retail environment focusing on consumer experience and product highlighting. Equipped with bespoke display systems.',
    areaSize: '1,000 sq ft',
    completionTime: '10 Weeks',
    scopeOfWork: 'Visual Merchandising, Track Lighting, Premium Flooring',
  },
  {
    id: 'corporate-lobby',
    name: 'CORPORATE LOBBY',
    category: 'Corporate Space',
    year: '2021',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&q=80&w=1400',
    description: 'A multi-zone lobby allowing guests to seamlessly transition through various waiting areas and reception desks to stimulate a grand first impression.',
    areaSize: '2,800 sq ft',
    completionTime: '18 Weeks',
    scopeOfWork: 'Reception Desk Design, Lounge Seating, Architectural Ceilings',
  },
  {
    id: 'minimalist-agency',
    name: 'MINIMALIST AGENCY',
    category: 'Creative Hub',
    year: '2020',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://images.unsplash.com/photo-1611324062122-076b1076c6cc?auto=format&fit=crop&q=80&w=1400',
    description: 'A minimalist agency space designed for intense focus and creative flow. Features stark monochromatic finishes and concealed storage technology.',
    areaSize: '12,500 sq ft',
    completionTime: '24 Weeks',
    scopeOfWork: 'Monochrome Finishes, Hidden Storage, Polished Concrete',
  },
  {
    id: 'coworking-space',
    name: 'COWORKING SPACE',
    category: 'Shared Workspace',
    year: '2020',
    image: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&q=80&w=1400',
    imageBefore: 'https://images.unsplash.com/photo-1642720740716-15838461af15?auto=format&fit=crop&q=80&w=1400',
    description: 'A recreation of community centers, utilizing varied seating density and private phone booths to create an immersive dynamic experience indoors.',
    areaSize: '2,200 sq ft',
    completionTime: '15 Weeks',
    scopeOfWork: 'Phone Booths, Varied Furniture Layout, Coffee Bar Integration',
  },
]
